### PR TITLE
Restoring documentation removed from testing.framework classes.

### PR DESCRIPTION
**Pull request by lewijw**
If this documentation was removed deliberately, then that is OK I guess, but just in case it was removed by mistake, I have created this pull request to restore it.

### CODE REVIEW

**Comment by lewijw** [comment]
The travis build failed due to a timeout that was very unlikely related to documentation changes.  2/3 builds passed.  Here is the error:

testBasicPost[HTTP](org.apache.hc.core5.testing.nio.http.Http1IntegrationTest)  Time elapsed: 5.042 sec  <<< ERROR!

java.util.concurrent.TimeoutException

	at org.apache.hc.core5.testing.nio.http.Http1IntegrationTest.testBasicPost(Http1IntegrationTest.java:384)

**Comment by ok2c** [comment]
This has certainly nothing to do with your changes. It may not even be a bug. It is conceivable that server was overloaded and the request timed out after 5 seconds.

**Comment by lewijw** [comment]
I don't see how to rerun it, or is that necessary?

**Comment by ok2c** [comment]
I think Gary owns the Travis CI job and only he can trigger job executions. Ignore it for now.

**Comment by lewijw** [comment]
Can we try to rerun the Travis build?

**Pull request closed without merging**
